### ISSUE TITLE
ZorinOS

### ISSUE THREAD

**Issue by hdt25** [krmanik/Manjaro-Linux-on-Android#7]
You should bring zorin os to Android. Your manjaro linux for android project is very much best I have ever seen before.
Maybe you should bring other distros like zorin , elementary , Mint  that are not brought till date to Android. This work will be much more appreciated.

**Comment by infinyte7** [comment]
I have tried to build it but there are errors I have also  tried to fix it but didn't work.

These os are still in development. zorin and elementary are based on ubuntu. 

This is repository I have created and tried for zorin and elementary. I will try again later with different desktop environment because elementary uses gnome and I don't know gnome will work in proot in termux or not? I have extracted and tried to proot into the filesystem then installed `tightvncserver` using termux but gnome-session needs `systemctl` in elementary?

https://github.com/infinyte7/rootfs-arm64

More info
- https://github.com/meisenzahl/elementary-os-unofficial/blob/master/hera/arm64/raspi4/build.sh
- https://locness.duckdns.org/wiki/doku.php?id=zorinraspi
